sudo: required
dist: trusty
language: bash
services: docker
env:
  - DOCKER_COMPOSE_VERSION=1.17.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

stages:
  - deploy

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

script:
  - docker-compose -f docker/docker-compose.build.yml build
  - docker-compose -f docker/docker-compose.build.yml push

after_script:
  - docker images
  - echo "Push docker images done!"

before_deploy:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  #- echo -e "\n" | ssh-add ~/.ssh/id_rsa & echo -e "\n"
  - echo 'echo ""' > ~/.echo_ps && chmod 700 ~/.echo_ps
  - cat ~/.ssh/id_rsa | SSH_ASKPASS=~/.echo_ps ssh-add -
  - ssh-keyscan -H 'travis-ci.com' >> ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chmod +x deploy.sh
deploy:
  provider: script
  script: REMOTE_HOST=$REMOTE_HOST REMOTE_USER=postman17 PROJECT_DIR=/test PROJECT_PROFILE=stage bash ./deploy.sh
  on:
    branch: master


after_deploy:
  - docker ps
