version: '3'

services:

  nginx:
    build: {context: ../, dockerfile: docker/nginx/Dockerfile}
    volumes:
      - ../media:/media
      - ../static:/static
    depends_on:
      - app
    ports:
      - "8044:80"

  app:
    build: {context: ../, dockerfile: docker/test/Dockerfile}
    volumes:
      - ../media:/media
      - ../static:/static
    env_file:
      - ../.env
    depends_on:
      - postgresql

  postgresql:
    image: postgres:11.1-alpine
    env_file: ../.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"